### ISSUE TITLE
`Dúvida` Criação de registro para escrituração do LCPDR

### ISSUE THREAD

**Issue by OtavioVB** [Eficaz-Sistemas/EficazFramework.SPED#28]
Na documentação do projeto possui um exemplo para criação do registro dessa forma:

![image](https://user-images.githubusercontent.com/101956836/193136942-0b86a58e-4daa-408d-b6ba-eb051d87924f.png)

No entanto, por que existe a criação do registro como nulo, sendo que no método override do construtor, não cai dentro do `If`:
![image](https://user-images.githubusercontent.com/101956836/193137145-015965af-412d-4c47-9257-047b52ed8737.png)

Por qual motivo está havendo o override dessa classe base `registro`?

**Comment by HClausing** [comment]
Olá @OtavioVB !

Este argumento utilizado no construtor é utilizado pela classe Escrituracao no ato da leitura/parse de algum arquivo para montagem das classes.

Ex:
```
System.IO.Stream stream = System.IO.File.OpenRead(@"C:\SPED\algumLcdprPreenchidoParaLeitura.txt");  
EficazFramework.SPED.Schemas.LCDPR.Escrituracao escrituracao = new();  
escrituracao.Encoding = System.Text.Encoding.Default; //opcional  
await escrituracao.LeArquivo(stream); 
```
 A última linha acima realiza um loop em cada linha de um arquivo txt existente, cria uma instância de Registro conforme o tipo de registro dos quatro primeiro caracteres, informando a string completa da linha para este construtor, que já irá utilizar o método .LeParametros() para popular as properties do Registro.

**Comment by HClausing** [comment]
Olá @OtavioVB ! 

Me esqueci de responde a esta dúvida:
> Por qual motivo está havendo o override dessa classe base registro?

R: Existe uma classe abstrata chamada Escrituracao, nas quais todas as demais (baseadas nos schemas que geram arquivos TXT), que contém métodos LeArquivo(), EscreveArquivo() e Dicionários de todos os registros Lidos ou em fila para escrita nos streams. Daí a necessidade de que todo registro dentro de uma escrituração tenha uma classe em comum. 

Além do mais, a própria classe abstrata Registro possui membros abstratos/virtuais EscreveLinha() (para formar o texto que deve ir para o stream) e LeParametros() (para popular suas propriedades conforme a string obtida do stream.ReadLine() ). 

A classe abstrata Escrituracao, quando executa LeArquivo() faz a leitura linha a linha da stream, cria uma instância de Registro (utilizando o construtor linha) e já popula as propriedades deste registro pelo método LeParametros().
